version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: foo_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: nodemon server.js -L --ignore 'public/*'
    depends_on:
      - postgres
    networks:
      - foo_net
      - default
    ports:
      - 3333:3333

  postgres:
    build: .docker/postgres-dev/.
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: foo_postgres
    ports:
      - 5432:5432
    networks:
      - foo_net
      - default
    volumes:
      - "postgre-data:/var/lib/postgresql"

volumes:
  postgre-data:
networks:
  foo_net:
    driver: bridge
